name: calendar_schedular
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: 3.1.2 # 달력 기능을 제공하는 플러그인
  intl: 0.19.0 # 다국어화 기능을 제공하는 플러그인
  drift_flutter: 0.1.0 # Drift ORM 플러그인
  path_provider: 2.1.5 # SQLite 데이터베이스 플러그인
  path: 1.9.1 # 경로 관련 기능을 제공하는 플러그인
  get_it: 8.0.2 # 경로 관련 기능을 제공하는 플러그인
  dio: 5.7.0 # 네트워크 요청을 가능하게 하는 플러그인
  provider: 6.1.2 # 글로벌 상태 관리를 가능하게 하는 플러그인
  uuid: 4.5.1 # UUID를 생성 할 수 있게 해주는 플러그인

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: 2.21.0 # Drift 코드 생성 기능 관련 플러그인
  build_runner: 2.4.13 # 플러터에서 코드 생성 기능을 제공해주는 플러그인

flutter:
  uses-material-design: true
